-- =====================================================================
-- TogetherTrip 스키마 (canonical)
-- 규칙
--   * 모든 테이블은 BaseEntity 기준 audit 컬럼 보유:
--       created_at / updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ
--   * 시각 컬럼은 전부 TIMESTAMPTZ (엔티티 java.time.Instant 매핑)
--   * 금액 DECIMAL(19,2), 환율 DECIMAL(19,6)
--   * spring.sql.init.separator = ";" 이므로 모든 statement 는 ; 로 종료
--   * mode: always 환경에서 매 기동 실행되므로 IF NOT EXISTS 로 멱등 보장
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255),
    nickname          VARCHAR(50) NOT NULL,
    profile_image_url VARCHAR(500),
    role              VARCHAR(20) NOT NULL,
    status            VARCHAR(20) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ
);

-- ---------------------------------------------------------------------
-- oauth_accounts
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS oauth_accounts
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    provider          VARCHAR(20)  NOT NULL,
    provider_user_id  VARCHAR(100) NOT NULL,
    email             VARCHAR(255),
    nickname          VARCHAR(50),
    profile_image_url VARCHAR(500),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT fk_oauth_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_oauth_accounts_provider_user
    ON oauth_accounts (provider, provider_user_id)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- trips
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trips
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id BIGINT       NOT NULL,
    name               VARCHAR(100) NOT NULL,
    default_currency   VARCHAR(3)   NOT NULL,
    start_date         DATE,
    end_date           DATE,
    expense_version    BIGINT       NOT NULL DEFAULT 0,
    settlement_status  VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    settled_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT fk_trips_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users (id)
);

-- ---------------------------------------------------------------------
-- trip_countries
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trip_countries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id      BIGINT       NOT NULL,
    country_code VARCHAR(2)   NOT NULL,
    country_name VARCHAR(100) NOT NULL,
    sort_order   INT          NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    CONSTRAINT fk_trip_countries_trip FOREIGN KEY (trip_id) REFERENCES trips (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trip_countries_trip_country
    ON trip_countries (trip_id, country_code)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- trip_participants
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trip_participants
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id            BIGINT      NOT NULL,
    user_id            BIGINT,
    display_name       VARCHAR(50) NOT NULL,
    profile_image_url  VARCHAR(500),
    participant_type   VARCHAR(20) NOT NULL,
    participant_status VARCHAR(20) NOT NULL,
    joined_at          TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT fk_trip_participants_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_trip_participants_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trip_participants_trip_user
    ON trip_participants (trip_id, user_id)
    WHERE user_id IS NOT NULL AND deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- transactions (원천 거래 데이터)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transactions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id            BIGINT         NOT NULL,
    created_by_user_id BIGINT         NOT NULL,
    transaction_type   VARCHAR(30)    NOT NULL,
    amount             DECIMAL(19, 2) NOT NULL,
    currency           VARCHAR(3)     NOT NULL,
    exchange_rate      DECIMAL(19, 6) NOT NULL,
    base_amount        DECIMAL(19, 2) NOT NULL,
    category           VARCHAR(30),
    description        TEXT,
    occurred_at        TIMESTAMPTZ    NOT NULL,
    location           GEOGRAPHY(POINT, 4326),
    place_name         VARCHAR(100),
    version            BIGINT         NOT NULL DEFAULT 0,
    status             VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT fk_transactions_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_transactions_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_transactions_trip_occurred_at
    ON transactions (trip_id, occurred_at)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_transactions_location
    ON transactions USING GIST (location);

-- ---------------------------------------------------------------------
-- transaction_payments (결제자)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transaction_payments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id      BIGINT         NOT NULL,
    trip_participant_id BIGINT         NOT NULL,
    amount              DECIMAL(19, 2) NOT NULL,
    currency            VARCHAR(3)     NOT NULL,
    exchange_rate       DECIMAL(19, 6) NOT NULL,
    base_amount         DECIMAL(19, 2) NOT NULL,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT fk_transaction_payments_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_transaction_payments_participant FOREIGN KEY (trip_participant_id) REFERENCES trip_participants (id)
);

CREATE INDEX IF NOT EXISTS idx_transaction_payments_transaction
    ON transaction_payments (transaction_id)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- transaction_shares (부담자)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transaction_shares
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id      BIGINT         NOT NULL,
    trip_participant_id BIGINT         NOT NULL,
    share_amount        DECIMAL(19, 2) NOT NULL,
    base_share_amount   DECIMAL(19, 2) NOT NULL,
    share_ratio         DECIMAL(7, 4),
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT fk_transaction_shares_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_transaction_shares_participant FOREIGN KEY (trip_participant_id) REFERENCES trip_participants (id)
);

CREATE INDEX IF NOT EXISTS idx_transaction_shares_transaction
    ON transaction_shares (transaction_id)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- transaction_events (거래 변경 이력)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transaction_events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id     BIGINT      NOT NULL,
    trip_id            BIGINT      NOT NULL,
    event_type         VARCHAR(30) NOT NULL,
    aggregate_version  BIGINT      NOT NULL,
    payload            JSONB       NOT NULL,
    created_by_user_id BIGINT      NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT fk_transaction_events_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_transaction_events_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_transaction_events_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users (id),
    CONSTRAINT uk_transaction_events_version UNIQUE (transaction_id, aggregate_version)
);

-- ---------------------------------------------------------------------
-- trip_participant_balance_summaries (정산 미리보기 증분 집계)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trip_participant_balance_summaries
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id             BIGINT         NOT NULL,
    trip_participant_id BIGINT         NOT NULL,
    paid_base_amount    DECIMAL(19, 2) NOT NULL DEFAULT 0,
    share_base_amount   DECIMAL(19, 2) NOT NULL DEFAULT 0,
    net_base_amount     DECIMAL(19, 2) NOT NULL DEFAULT 0,
    projection_version  BIGINT         NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT fk_balance_summaries_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_balance_summaries_participant FOREIGN KEY (trip_participant_id) REFERENCES trip_participants (id),
    CONSTRAINT uk_balance_summaries_trip_participant UNIQUE (trip_id, trip_participant_id)
);

-- ---------------------------------------------------------------------
-- settlements (정산 스냅샷)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settlements
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id                  BIGINT         NOT NULL,
    status                   VARCHAR(20)    NOT NULL,
    trip_expense_version     BIGINT         NOT NULL,
    calculation_version      VARCHAR(30)    NOT NULL,
    base_currency            VARCHAR(3)     NOT NULL,
    total_expense_amount     DECIMAL(19, 2) NOT NULL DEFAULT 0,
    total_common_fund_amount DECIMAL(19, 2) NOT NULL DEFAULT 0,
    total_share_amount       DECIMAL(19, 2) NOT NULL DEFAULT 0,
    snapshot_payload         JSONB          NOT NULL,
    confirmed_at             TIMESTAMPTZ,
    confirmed_by_user_id     BIGINT,
    share_token              VARCHAR(100),
    created_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at               TIMESTAMPTZ,
    CONSTRAINT fk_settlements_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_settlements_confirmed_by_user FOREIGN KEY (confirmed_by_user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_settlements_trip_status
    ON settlements (trip_id, status)
    WHERE deleted_at IS NULL;

-- CONFIRMED 정산은 여행방당 하나만 가능
CREATE UNIQUE INDEX IF NOT EXISTS uk_settlements_confirmed_trip
    ON settlements (trip_id)
    WHERE status = 'CONFIRMED' AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_settlements_share_token
    ON settlements (share_token)
    WHERE share_token IS NOT NULL AND deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- settlement_transfers (송금 체크리스트)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settlement_transfers
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id           BIGINT         NOT NULL,
    sender_participant_id   BIGINT         NOT NULL,
    receiver_participant_id BIGINT         NOT NULL,
    amount                  DECIMAL(19, 2) NOT NULL,
    currency                VARCHAR(3)     NOT NULL,
    status                  VARCHAR(20)    NOT NULL,
    sender_confirmed_at     TIMESTAMPTZ,
    receiver_confirmed_at   TIMESTAMPTZ,
    completed_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at              TIMESTAMPTZ,
    CONSTRAINT fk_settlement_transfers_settlement FOREIGN KEY (settlement_id) REFERENCES settlements (id),
    CONSTRAINT fk_settlement_transfers_sender FOREIGN KEY (sender_participant_id) REFERENCES trip_participants (id),
    CONSTRAINT fk_settlement_transfers_receiver FOREIGN KEY (receiver_participant_id) REFERENCES trip_participants (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_settlement_transfers_pair
    ON settlement_transfers (settlement_id, sender_participant_id, receiver_participant_id)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- posts (커뮤니티 게시글)  ── 구 trip_posts
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS posts
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id               BIGINT      NOT NULL,
    transaction_id        BIGINT,
    author_participant_id BIGINT      NOT NULL,
    content               TEXT,
    visibility            VARCHAR(20) NOT NULL DEFAULT 'TRIP_ONLY',
    post_type             VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT fk_posts_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_posts_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_posts_author_participant FOREIGN KEY (author_participant_id) REFERENCES trip_participants (id)
);

CREATE INDEX IF NOT EXISTS idx_posts_trip_created_at
    ON posts (trip_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_posts_transaction
    ON posts (transaction_id)
    WHERE transaction_id IS NOT NULL AND deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- post_attachments  ── 구 trip_post_attachments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS post_attachments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT        NOT NULL,
    attachment_type VARCHAR(20)   NOT NULL,
    file_url        VARCHAR(1000) NOT NULL,
    thumbnail_url   VARCHAR(1000),
    file_size       BIGINT,
    mime_type       VARCHAR(100),
    sort_order      INT           NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT fk_post_attachments_post FOREIGN KEY (post_id) REFERENCES posts (id)
);

CREATE INDEX IF NOT EXISTS idx_post_attachments_post
    ON post_attachments (post_id)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- post_comments  ── 구 trip_post_comments
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS post_comments
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id               BIGINT      NOT NULL,
    author_participant_id BIGINT      NOT NULL,
    content               TEXT        NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT fk_post_comments_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_post_comments_author_participant FOREIGN KEY (author_participant_id) REFERENCES trip_participants (id)
);

CREATE INDEX IF NOT EXISTS idx_post_comments_post_created_at
    ON post_comments (post_id, created_at)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- post_likes  ── 구 trip_post_likes
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS post_likes
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id             BIGINT      NOT NULL,
    trip_participant_id BIGINT      NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT fk_post_likes_participant FOREIGN KEY (trip_participant_id) REFERENCES trip_participants (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_post_likes_post_participant
    ON post_likes (post_id, trip_participant_id)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------
-- outbox_events (Transactional Outbox)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id   BIGINT      NOT NULL,
    event_type     VARCHAR(50) NOT NULL,
    payload        JSONB       NOT NULL,
    status         VARCHAR(20) NOT NULL,
    retry_count    INT         NOT NULL DEFAULT 0,
    published_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_outbox_events_status_created_at
    ON outbox_events (status, created_at);
