-- =====================================================================
-- TogetherTrip 1st MVP schema
-- BaseEntity columns: created_at / updated_at / deleted_at
-- =====================================================================

CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255),
    nickname          VARCHAR(50)  NOT NULL,
    gender            VARCHAR(20),
    birth_date        DATE,
    profile_image_url VARCHAR(500),
    phone_number      VARCHAR(30),
    phone_verified_at TIMESTAMPTZ,
    role              VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS oauth_accounts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL REFERENCES users (id),
    provider         VARCHAR(20)  NOT NULL,
    provider_user_id VARCHAR(100) NOT NULL,
    email            VARCHAR(255),
    nickname         VARCHAR(50),
    profile_image_url VARCHAR(500),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT uk_oauth_accounts_provider_provider_user_id UNIQUE (provider, provider_user_id)
);

CREATE TABLE IF NOT EXISTS user_agreements
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users (id),
    agreement_type VARCHAR(30) NOT NULL,
    agreed         BOOLEAN     NOT NULL DEFAULT false,
    agreed_at      TIMESTAMPTZ,
    revoked_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS trips
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id           BIGINT       NOT NULL REFERENCES users (id),
    title                   VARCHAR(100) NOT NULL,
    default_currency        VARCHAR(3)   NOT NULL,
    exchange_rate_base_date DATE,
    start_date              DATE,
    end_date                DATE,
    trip_status             VARCHAR(20)  NOT NULL DEFAULT 'PLANNED',
    settlement_status       VARCHAR(20)  NOT NULL DEFAULT 'NOT_STARTED',
    expense_version         BIGINT       NOT NULL DEFAULT 0,
    settled_at              TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at              TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS trip_invitations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id           BIGINT        NOT NULL REFERENCES trips (id),
    token             VARCHAR(100)  NOT NULL,
    invite_url        VARCHAR(1000) NOT NULL,
    created_by_user_id BIGINT       NOT NULL REFERENCES users (id),
    used_by_user_id   BIGINT        REFERENCES users (id),
    invitation_status VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    expires_at        TIMESTAMPTZ,
    used_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trip_invitations_token
    ON trip_invitations (token)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS trip_countries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id      BIGINT       NOT NULL REFERENCES trips (id),
    country_code VARCHAR(2)   NOT NULL,
    country_name VARCHAR(100) NOT NULL,
    sort_order   INT          NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trip_countries_trip_country
    ON trip_countries (trip_id, country_code)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS trip_participants
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id            BIGINT      NOT NULL REFERENCES trips (id),
    user_id            BIGINT      REFERENCES users (id),
    display_name       VARCHAR(50) NOT NULL,
    profile_image_url  VARCHAR(500),
    participant_role   VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    participant_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    joined_at          TIMESTAMPTZ,
    left_at            TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at         TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trip_participants_trip_user
    ON trip_participants (trip_id, user_id)
    WHERE user_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS trip_exchange_rates
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id         BIGINT         NOT NULL REFERENCES trips (id),
    base_currency   VARCHAR(3)     NOT NULL,
    target_currency VARCHAR(3)     NOT NULL,
    rate            DECIMAL(19, 6) NOT NULL,
    rate_date       DATE,
    source          VARCHAR(50),
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trip_exchange_rates_trip_currency_date
    ON trip_exchange_rates (trip_id, base_currency, target_currency, rate_date)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS transactions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id            BIGINT         NOT NULL REFERENCES trips (id),
    created_by_user_id BIGINT         NOT NULL REFERENCES users (id),
    transaction_type   VARCHAR(30)    NOT NULL DEFAULT 'EXPENSE',
    amount             DECIMAL(19, 2) NOT NULL,
    currency           VARCHAR(3)     NOT NULL,
    exchange_rate      DECIMAL(19, 6) NOT NULL,
    base_currency      VARCHAR(3)     NOT NULL,
    base_amount        DECIMAL(19, 2) NOT NULL,
    version            BIGINT         NOT NULL DEFAULT 0,
    status             VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_transactions_trip_created_at
    ON transactions (trip_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS posts
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id               BIGINT      NOT NULL REFERENCES trips (id),
    transaction_id        BIGINT      REFERENCES transactions (id),
    author_participant_id BIGINT      NOT NULL REFERENCES trip_participants (id),
    post_type             VARCHAR(20) NOT NULL,
    title                 VARCHAR(100),
    category              VARCHAR(30),
    content               TEXT,
    occurred_at           TIMESTAMPTZ,
    place_name            VARCHAR(100),
    latitude              DECIMAL(10, 7),
    longitude             DECIMAL(10, 7),
    comment_count         INT         NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at            TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_posts_trip_created_at
    ON posts (trip_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS post_comments
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id               BIGINT      NOT NULL REFERENCES posts (id),
    parent_comment_id     BIGINT      REFERENCES post_comments (id),
    author_participant_id BIGINT      NOT NULL REFERENCES trip_participants (id),
    content               TEXT        NOT NULL,
    comment_depth         INT         NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at            TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_post_comments_post_created_at
    ON post_comments (post_id, created_at)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS transaction_payments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id      BIGINT         NOT NULL REFERENCES transactions (id),
    trip_participant_id BIGINT         NOT NULL REFERENCES trip_participants (id),
    amount              DECIMAL(19, 2) NOT NULL,
    currency            VARCHAR(3)     NOT NULL,
    exchange_rate       DECIMAL(19, 6) NOT NULL,
    base_currency       VARCHAR(3)     NOT NULL,
    base_amount         DECIMAL(19, 2) NOT NULL,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_transaction_payments_transaction
    ON transaction_payments (transaction_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS transaction_shares
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id      BIGINT         NOT NULL REFERENCES transactions (id),
    trip_participant_id BIGINT         NOT NULL REFERENCES trip_participants (id),
    share_amount        DECIMAL(19, 2) NOT NULL,
    currency            VARCHAR(3)     NOT NULL,
    exchange_rate       DECIMAL(19, 6) NOT NULL,
    base_currency       VARCHAR(3)     NOT NULL,
    base_share_amount   DECIMAL(19, 2) NOT NULL,
    share_ratio         DECIMAL(7, 4),
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_transaction_shares_transaction
    ON transaction_shares (transaction_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS post_attachments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT        NOT NULL REFERENCES posts (id),
    attachment_type VARCHAR(20)   NOT NULL,
    file_url        VARCHAR(1000) NOT NULL,
    thumbnail_url   VARCHAR(1000),
    file_size       BIGINT,
    mime_type       VARCHAR(100),
    sort_order      INT           NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_post_attachments_post
    ON post_attachments (post_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS transaction_events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id     BIGINT      NOT NULL REFERENCES transactions (id),
    trip_id            BIGINT      NOT NULL REFERENCES trips (id),
    event_type         VARCHAR(30) NOT NULL,
    aggregate_version  BIGINT      NOT NULL,
    payload            JSONB       NOT NULL,
    created_by_user_id BIGINT      NOT NULL REFERENCES users (id),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT uk_transaction_events_version UNIQUE (transaction_id, aggregate_version)
);

CREATE TABLE IF NOT EXISTS trip_participant_balance_summaries
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id             BIGINT         NOT NULL REFERENCES trips (id),
    trip_participant_id BIGINT         NOT NULL REFERENCES trip_participants (id),
    paid_base_amount    DECIMAL(19, 2) NOT NULL DEFAULT 0,
    share_base_amount   DECIMAL(19, 2) NOT NULL DEFAULT 0,
    net_base_amount     DECIMAL(19, 2) NOT NULL DEFAULT 0,
    projection_version  BIGINT         NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT uk_balance_summaries_trip_participant UNIQUE (trip_id, trip_participant_id)
);

CREATE TABLE IF NOT EXISTS settlements
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id              BIGINT         NOT NULL REFERENCES trips (id),
    status               VARCHAR(20)    NOT NULL,
    trip_expense_version BIGINT         NOT NULL,
    calculation_version  VARCHAR(30)    NOT NULL,
    base_currency        VARCHAR(3)     NOT NULL,
    total_expense_amount DECIMAL(19, 2) NOT NULL DEFAULT 0,
    total_share_amount   DECIMAL(19, 2) NOT NULL DEFAULT 0,
    snapshot_payload     JSONB          NOT NULL,
    share_token          VARCHAR(100),
    confirmed_at         TIMESTAMPTZ,
    confirmed_by_user_id BIGINT         REFERENCES users (id),
    created_at           TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at           TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_settlements_confirmed_trip
    ON settlements (trip_id)
    WHERE status = 'CONFIRMED' AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_settlements_share_token
    ON settlements (share_token)
    WHERE share_token IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS settlement_transfers
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id           BIGINT         NOT NULL REFERENCES settlements (id),
    sender_participant_id   BIGINT         NOT NULL REFERENCES trip_participants (id),
    receiver_participant_id BIGINT         NOT NULL REFERENCES trip_participants (id),
    amount                  DECIMAL(19, 2) NOT NULL,
    currency                VARCHAR(3)     NOT NULL,
    status                  VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    sender_confirmed_at     TIMESTAMPTZ,
    receiver_confirmed_at   TIMESTAMPTZ,
    auto_confirmed          BOOLEAN        NOT NULL DEFAULT false,
    auto_confirm_reason     VARCHAR(100),
    completed_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at              TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_settlement_transfers_pair
    ON settlement_transfers (settlement_id, sender_participant_id, receiver_participant_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id   BIGINT      NOT NULL,
    event_type     VARCHAR(50) NOT NULL,
    payload        JSONB       NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    retry_count    INT         NOT NULL DEFAULT 0,
    published_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_outbox_events_status_created_at
    ON outbox_events (status, created_at);
