package com.togethertrip.main.global.outbox.domain

enum class OutboxEventType {
    TRIP_PARTICIPANTS_ADDED,
    TRIP_PARTICIPANT_JOINED,
    TRIP_PARTICIPANT_REMOVED,
    POST_CREATED,
    EXPENSE_POST_CREATED,
    POST_COMMENT_CREATED,
    SETTLEMENT_CONFIRMED,
    SETTLEMENT_TRANSFER_CONFIRMED_BY_SENDER,
    SETTLEMENT_TRANSFER_COMPLETED,
}
