ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone_number_encrypted TEXT,
    ADD COLUMN IF NOT EXISTS phone_number_encryption_version VARCHAR(30),
    ADD COLUMN IF NOT EXISTS phone_number_masked VARCHAR(30),
    ADD COLUMN IF NOT EXISTS phone_number_hash VARCHAR(64),
    ADD COLUMN IF NOT EXISTS phone_number_hash_version VARCHAR(30);

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_verified_phone_hash
    ON users (phone_number_hash)
    WHERE phone_number_hash IS NOT NULL
      AND phone_verified_at IS NOT NULL
      AND deleted_at IS NULL;

CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_INSTANCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ START WITH 1 INCREMENT BY 1;

SELECT setval(
    'BATCH_JOB_INSTANCE_SEQ',
    COALESCE((SELECT MAX(JOB_INSTANCE_ID) FROM BATCH_JOB_INSTANCE), 0) + 1,
    false
);

SELECT setval(
    'BATCH_JOB_EXECUTION_SEQ',
    COALESCE((SELECT MAX(JOB_EXECUTION_ID) FROM BATCH_JOB_EXECUTION), 0) + 1,
    false
);

SELECT setval(
    'BATCH_STEP_EXECUTION_SEQ',
    COALESCE((SELECT MAX(STEP_EXECUTION_ID) FROM BATCH_STEP_EXECUTION), 0) + 1,
    false
);
