CREATE TABLE IF NOT EXISTS trip_recaps
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id              BIGINT      NOT NULL REFERENCES trips (id),
    requested_by_user_id BIGINT      NOT NULL REFERENCES users (id),
    style                VARCHAR(20) NOT NULL,
    status               VARCHAR(20) NOT NULL,
    scene_count          INT         NOT NULL DEFAULT 0,
    attempt_count        INT         NOT NULL DEFAULT 1,
    failure_reason       VARCHAR(1000),
    completed_at         TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at           TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trip_recaps_trip
    ON trip_recaps (trip_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_trip_recaps_status_updated_at
    ON trip_recaps (status, updated_at)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS trip_recap_scenes
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recap_id            BIGINT        NOT NULL REFERENCES trip_recaps (id),
    scene_order         INT           NOT NULL,
    style               VARCHAR(20)   NOT NULL,
    image_object_key    VARCHAR(500)  NOT NULL,
    image_url           VARCHAR(1000) NOT NULL,
    scene_description   TEXT          NOT NULL,
    image_prompt        TEXT          NOT NULL,
    generation_provider VARCHAR(50)   NOT NULL,
    generation_model    VARCHAR(100)  NOT NULL,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_trip_recap_scenes_recap_order
    ON trip_recap_scenes (recap_id, scene_order)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_trip_recap_scenes_recap_order
    ON trip_recap_scenes (recap_id, scene_order)
    WHERE deleted_at IS NULL;
