ALTER TABLE users
    ADD COLUMN IF NOT EXISTS moderation_restricted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS moderation_restricted_until TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS moderation_restriction_reason VARCHAR(500);

ALTER TABLE posts
    ADD COLUMN IF NOT EXISTS moderation_hidden_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS moderation_deleted_at TIMESTAMPTZ;

ALTER TABLE post_comments
    ADD COLUMN IF NOT EXISTS moderation_hidden_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS moderation_deleted_at TIMESTAMPTZ;

ALTER TABLE trip_recaps
    ADD COLUMN IF NOT EXISTS moderation_hidden_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS moderation_deleted_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS moderation_reports
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id             BIGINT       NOT NULL REFERENCES trips (id),
    reporter_user_id    BIGINT       NOT NULL REFERENCES users (id),
    target_type         VARCHAR(30)  NOT NULL,
    target_id           BIGINT       NOT NULL,
    target_user_id      BIGINT       NOT NULL REFERENCES users (id),
    reason              VARCHAR(30)  NOT NULL,
    description         VARCHAR(1000),
    status              VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    handled_by_user_id  BIGINT       REFERENCES users (id),
    handled_at          TIMESTAMPTZ,
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT ck_moderation_reports_target_type
        CHECK (target_type IN ('POST', 'COMMENT', 'USER', 'TRIP_RECAP')),
    CONSTRAINT ck_moderation_reports_reason
        CHECK (reason IN ('SPAM', 'HARASSMENT', 'HATE_SPEECH', 'SEXUAL_CONTENT', 'VIOLENCE', 'PRIVACY', 'OTHER')),
    CONSTRAINT ck_moderation_reports_status
        CHECK (status IN ('PENDING', 'IN_REVIEW', 'RESOLVED', 'REJECTED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_moderation_reports_active
    ON moderation_reports (reporter_user_id, trip_id, target_type, target_id)
    WHERE deleted_at IS NULL AND status IN ('PENDING', 'IN_REVIEW');

CREATE INDEX IF NOT EXISTS idx_moderation_reports_queue
    ON moderation_reports (status, created_at, id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS moderation_report_audits
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id           BIGINT       NOT NULL REFERENCES moderation_reports (id),
    actor_user_id       BIGINT       NOT NULL REFERENCES users (id),
    action              VARCHAR(40)  NOT NULL,
    previous_status     VARCHAR(30),
    next_status         VARCHAR(30)  NOT NULL,
    note                VARCHAR(1000),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_moderation_report_audits_report
    ON moderation_report_audits (report_id, created_at, id);

CREATE OR REPLACE FUNCTION reject_moderation_report_audit_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'moderation_report_audits is append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_moderation_report_audits_append_only ON moderation_report_audits;
CREATE TRIGGER trg_moderation_report_audits_append_only
    BEFORE UPDATE OR DELETE ON moderation_report_audits
    FOR EACH ROW EXECUTE FUNCTION reject_moderation_report_audit_mutation();

CREATE TABLE IF NOT EXISTS user_blocks
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_user_id     BIGINT      NOT NULL REFERENCES users (id),
    blocked_user_id     BIGINT      NOT NULL REFERENCES users (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT ck_user_blocks_not_self CHECK (blocker_user_id <> blocked_user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_blocks_active
    ON user_blocks (blocker_user_id, blocked_user_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_user_blocks_reverse
    ON user_blocks (blocked_user_id, blocker_user_id)
    WHERE deleted_at IS NULL;
