CREATE TABLE IF NOT EXISTS exchange_rates
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency   VARCHAR(3)     NOT NULL,
    target_currency VARCHAR(3)     NOT NULL,
    rate            DECIMAL(19, 6) NOT NULL,
    rate_date       DATE           NOT NULL,
    source          VARCHAR(50),
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_exchange_rates_currency_date
    ON exchange_rates (base_currency, target_currency, rate_date)
    WHERE deleted_at IS NULL;
