CREATE TABLE IF NOT EXISTS exchange_rate_import_runs
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider               VARCHAR(50) NOT NULL,
    rate_date              DATE        NOT NULL,
    status                 VARCHAR(20) NOT NULL,
    attempt_count          INT         NOT NULL DEFAULT 0,
    row_count              INT         NOT NULL DEFAULT 0,
    upsert_count           INT         NOT NULL DEFAULT 0,
    last_result_code       VARCHAR(20),
    last_error_message     VARCHAR(500),
    started_at             TIMESTAMPTZ,
    finished_at            TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at             TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_exchange_rate_import_runs_provider_date
    ON exchange_rate_import_runs (provider, rate_date)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_exchange_rate_import_runs_status_date
    ON exchange_rate_import_runs (status, rate_date)
    WHERE deleted_at IS NULL;
