CREATE TABLE IF NOT EXISTS exchange_rate_backfill_jobs
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by                   BIGINT      NOT NULL,
    from_date                      DATE        NOT NULL,
    to_date                        DATE        NOT NULL,
    max_days_per_run               BIGINT      NOT NULL,
    pause_between_requests_millis  BIGINT      NOT NULL,
    status                         VARCHAR(20) NOT NULL,
    total_requested_days           BIGINT      NOT NULL DEFAULT 0,
    processed_days                 INT         NOT NULL DEFAULT 0,
    success_count                  INT         NOT NULL DEFAULT 0,
    failed_count                   INT         NOT NULL DEFAULT 0,
    no_data_count                  INT         NOT NULL DEFAULT 0,
    non_business_day_count         INT         NOT NULL DEFAULT 0,
    last_error_message             VARCHAR(500),
    started_at                     TIMESTAMPTZ,
    finished_at                    TIMESTAMPTZ,
    created_at                     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at                     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_exchange_rate_backfill_jobs_status_created
    ON exchange_rate_backfill_jobs (status, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_exchange_rate_backfill_jobs_requested_by_created
    ON exchange_rate_backfill_jobs (requested_by, created_at DESC)
    WHERE deleted_at IS NULL;
